#ifndef QTONEDRIVELIB_GLOBAL_H
#define QTONEDRIVELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef TEST_QTONEDRIVE

#if defined(QTONEDRIVELIB_LIBRARY)
#  define QTONEDRIVELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTONEDRIVELIBSHARED_EXPORT Q_DECL_IMPORT
#endif
#else
   #define QTONEDRIVELIBSHARED_EXPORT
#endif
#endif // QTONEDRIVELIB_GLOBAL_H
